### ISSUE TITLE
Add 'calculateAndCheckDiff' with pretty printed diffs?

### ISSUE THREAD

**Issue by chshersh** [hspec/hspec-expectations#30]
My proposal is to add `calculateAndCheckDiff :: Eq t => [t] -> [t] -> Expectation` function or something like that (and most likely with better name). The idea is that sometimes users want to compare big strings of text, about 100 lines each. Printing two big strings in the terminal output with the fact that they both aren't equal doesn't really help to find exact lines where they are not equal. One use case: compare code sources before and after refactoring. 

This function should run [`getGroupedDiff`](https://www.stackage.org/haddock/lts-8.21/Diff-0.3.4/Data-Algorithm-Diff.html#v:getGroupedDiff) and pretty print it if diff shows that lists diverge.

Similar things can be accomplished with [`tasty-golden`](https://hackage.haskell.org/package/tasty-golden-2.3.1.1/docs/Test-Tasty-Golden.html) package but it requires you to use `tasty` framework instead.

**Comment by sol** [comment]
I think this is something we might be able to address in `hspec-core` generically.  Say we could try suppress excessive output by default + add a flag `--show-full-diffs` in case the user wants to see the full values.

I'm not sure when I will have time to look into it though.  But I think definitely something that could be useful.

**Comment by sol** [comment]
I opened https://github.com/hspec/hspec/issues/449.
