### ISSUE TITLE
Comparing values that have `IORef` in them

### ISSUE THREAD

**Issue by FranklinChen** [hspec/hspec-expectations#32]
What is the recommended way to write a matcher to compare two values that have `IORef` in them and therefore have to be evaluated in `IO` both for equality comparison and showable diffs?

**Comment by sol** [comment]
Something like this:
```haskell
(readIORef actual `shouldReturn`) =<< readIORef expected
```

**Comment by FranklinChen** [comment]
I meant, if I have

```haskell
data List a = Nil | Cons (IORef a) (IORef (List a))
```
I want to write

```haskell
shouldBeEqList :: (Show a, Eq a) => List a -> List a -> Expectation
```

**Comment by sol** [comment]
@FranklinChen sorry for the late replay, there is no standard way of achieving this.

### Option 1
The easiest approach might be to convert your `List` to a regular Haskell list, say if you have

```haskell
toList :: List a -> [a]
```
you can do something like this:
```haskell
infix 1 `shouldBeEqList`

shouldBeEqList :: HasCallStack => (Eq a, Show a) => List a -> List a -> Expectation
shouldBeEqList actual expected = do
  (toList actual `shouldReturn`) =<< toList expected
```

### Option 2
If you have functions:

```haskell
eqList :: Eq a => List a -> List a -> IO Bool
showList :: Show a => List a -> List a -> IO String
```

then you can do something like:

#### Option 2.1
```haskell
shouldBeEqList :: HasCallStack => Show a => List a -> List a -> Expectation
shouldBeEqList actual expected = do
  (showList actual `shouldReturn`) =<< showList expected
```
We are ignoring the `Eq` instance here and instead rely on the fact that lists that look equal are equal and that lists that are not equal look different.

If that is not the case for some reason, you can do this instead:
#### Option 2.2
```haskell
shouldBeEqList :: HasCallStack => (Eq a, Show a) => List a -> List a -> Expectation
shouldBeEqList actual expected = do
  eq <- eqList actual expected
  unless eq $ throwIO (HUnitFailure location $ ExpectedButGot Nothing expectedMsg actualMsg)

location :: HasCallStack => Maybe SrcLoc
location = case reverse callStack of
  (_, loc) : _ -> Just loc
  [] -> Nothing
```
(look at https://hackage.haskell.org/package/HUnit-1.6.1.0/docs/src/Test.HUnit.Lang.html#assertEqual for the imports you will need)

We should probably export more things from `HUnit` to make this kind of things easier.

**Comment by sol** [comment]
I opened https://github.com/hspec/HUnit/issues/29.
