### ISSUE TITLE
Add `shouldReturnSatisfying`

### ISSUE THREAD

**Issue by chshersh** [hspec/hspec-expectations#33]
It would be nice to have the following function:

```haskell
shouldReturnSatisfying :: (HasCallStack, Show a, Eq a) => IO a -> (a -> Bool) -> Expectation
```

I found that I need such function quite often.

**Comment by sol** [comment]
Hey! Thanks for using `hspec` and opening this issue!

I'm not opposed, but not convinced neither. 

What I do in situations like this is:
```haskell
action >>= (`shouldSatisfy` p)
```
For comparison:
```haskell
action `shouldReturnSatisfying` p
```

Not a big win.  Do you think it justifies increasing the API surface?

For sure we can add it to `    Test.Hspec.Expectations.Contrib`, if that is an option for you.

And we should meet up when I'm in Singapore again!

**Comment by chshersh** [comment]
I find `hspec` convenient to use. I like its declarative nature and ability to create hierarchical trees :slightly_smiling_face: And, to be honest, there are not many testing libraries in the Haskell ecosystem...

Another alternative is to write:

```haskell
p <$> action `shouldReturn` True
```

Though the win is not about line length but more about code readability and less noise with `()`. I understand that this function might not be the right candidate for expanding the existing interface. The idea with `Contrib` module seems useful! I think there exist a potentially significant number of valuable predicates. And if there's  a place where such functions can be included without much thinking, that would be nice :+1: 

Unfortunately, I will leave Singapore quite soon, so we probably will meet in another place:slightly_smiling_face:

**Comment by sol** [comment]
Ok, great!  If you feel the urge to do something here then please feel free to open a PR.
