### ISSUE TITLE
Test with new 8.x GHCs, new Cabal 3.x in CI

### ISSUE THREAD

**Issue by declension** [hspec/hspec-expectations#36]
Hi!

It'd be great to configure the project CI to test against more recent GHCs (currently stops at `8.0.1`) and Cabal (currently `1.24`) - e.g. `8.10` and `3.2`. Not sure how many in between are worth checking / whether to drop any older ones.

### Potential Inspiration
* [`bytestring`'s version](https://github.com/haskell/bytestring/blob/master/.travis.yml)
* Or (more complex): [`lens`'s](https://github.com/ekmett/lens/blob/master/.travis.yml)

**Comment by sol** [comment]
This is done by now.
