### ISSUE TITLE
Test suite build failure with GHC 7.8

### ISSUE THREAD

**Issue by andreasabel** [hspec/hspec-expectations#66]
```
$ $ cabal build -w ghc-7.8.4
...
Building test suite 'spec' for hspec-expectations-0.8.4...
...
test/Helper.hs:11:22:
    Illegal tuple constraint: HasCallStack
      (Use ConstraintKinds to permit this)
    In the type signature for ‘expectationFailed’:
      expectationFailed :: HasCallStack =>
                           FailureReason -> HUnitFailure -> Bool
Error: cabal: Failed to build test:spec from hspec-expectations-0.8.4.
```

**Comment by sol** [comment]
Thanks @andreasabel 🙏

We are not testing anything older than `7.10` on CI Anymore. This is why this went unnoticed.

Do you care about `7.8` support? It would be easy to retain, but we would probably want to test it on CI somehow.

**Comment by andreasabel** [comment]
Welcome, @sol.

> Do you care about `7.8` support?

No, not really.  I have some old stable packages that I maintain and they have CI going back as far as 7.0, but it is not very reasonable to support 7.8 and older.  As long as they work without problems, I keep these old CI instances, but once I face problems, I should drop them.

However, the bounds of dependencies should be correct as far as possible so that cabal does not pick up wrong versions.  Unfortunately, we do not have the hackage matrix anymore to test bounds routinely.  So bounds might rot, and once in a while me might stumble on incorrect bounds that lead to build failures, such as here.

Not sure what the best approach to correct bounds is.  @nomeata argues that the bounds should reflect of what is tested in CI, facilitated by his tool https://github.com/nomeata/cabal-plan-bounds.  This however, might lead to bounds that are stricter than the truth and might exclude correct uses of a package, so I am hesitant to fully embrace this philosophy.

**Comment by sol** [comment]
> However, the bounds of dependencies should be correct as far as possible so that cabal does not pick up wrong versions.

agreed.

>  @nomeata argues that the bounds should reflect of what is tested in CI

We can apply the `base` bound to the package as a whole. I think that could make some CPP and the `call-stack` dependency obsolete.  PRs welcome (I might do it myself eventually if/when I need to touch the code anyway).

**Comment by andreasabel** [comment]
> We can apply the `base` bound to the package as a whole. I think that could make some CPP and the `call-stack` dependency obsolete. PRs welcome (I might do it myself eventually if/when I need to touch the code anyway).

Typically, I don't _actively_ remove support for older versions; I do it lazily, when supporting them becomes a nuisance...
